### ISSUE TITLE
Camera not open , i found blank view when App Open.

### ISSUE THREAD

**Issue by yeminsoe** [dns-technologies/mlkit_scanner#10]
First of all, I would like to thank you for your skill. 
but I faced one issues on my app>>
Camera not open , i found blank view when App Open.

**Comment by skrjt** [comment]
Hi, @yeminsoe !
Blank view is usually shown on hot restart / hot reload. This is due to the technical features of the camera, probably something crashes or cannot be recreated.
I found an open issue in flutter, probably without it it will not be possible to correctly hot restart the application:
https://github.com/flutter/flutter/issues/10437

**Comment by skrjt** [comment]
So, I found some examples, where possible, I'll try to explore

**Comment by skrjt** [comment]
@yeminsoe , this issues will be fixed at https://github.com/dns-technologies/mlkit_scanner/pull/14

**Comment by skrjt** [comment]
Issue was fixed
