### ISSUE TITLE
qr code not scanning in dark mode 

### ISSUE THREAD

**Issue by lan2001** [dns-technologies/mlkit_scanner#8]
`mlkit_scanner 0.3.2`

Describe the bug
Qr code not scanning in dark mode
that same Qr code scanning without dark mode

QR code picture
![a6baeda83bc4104045a1a67b4d43b6f](https://user-images.githubusercontent.com/29707716/187347369-273a3f23-00b3-4094-ad2e-8f2a291b3485.png)

**Comment by skrjt** [comment]
Hi, @lan2001 !
I looked at your problem, the scanner really does not scan this qr code.
We are using google ml kit to get information from barcodes, you can download the official repository, run the example and see if it can recognize your qr:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin.git
![Uploading Screenshot_2022-09-21-14-14-39-661_com.google_mlkit_example.jpg…]()

P.S. I tried, sometimes it really scans it, though it's not entirely clear what it depends on.

If it really works better in the official repository, then something can be done about it, otherwise, it seems that it is better to create this issue with them.

Thanks!

**Comment by skrjt** [comment]
Looks like the problem is not on our side
